### PR TITLE
Adds md5 check to downloaded update to make sure the download is what…

### PR DESCRIPTION
**Pull request by Flat**
… it is supposed to be. Also fixes typo in error message.

Signed-off-by: Ken Swenson <flat@imo.uto.moe>

### CODE REVIEW

**Comment by tylerflint** [comment]
This looks great! Thanks for doing this. I'm sure we'll review and merge this in tomorrow. 

Thanks again!

**Comment by Flat** [comment]
Hey no problem. This looks like a great project and I like helping out!

**Comment by sdomino** [comment]
@Flat this looks really good. I'll go ahead and merge it in.

**Comment by sdomino** [comment]
Resolves issue #116

**Pull request merged**
