### PR TITLE
Make sure vbomange installed with $VBOX_MSI_INSTALL_PATH is defined

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by sdomino** [comment]
This looks great.

@mattn - we do a similar check for vagrant in util/vagrant.go, do you know if we would need to make a similar update there as well?

**Comment by mattn** [comment]
updated.

**Comment by mattn** [comment]
oops. sorry. debug message ramains. will fix soon

**Comment by mattn** [comment]
Ah, probably it should be same on non-windows OSs.

**Comment by mattn** [comment]
done

**Comment by sdomino** [comment]
@mattn looks good. I like exec.Lookpath(), I wonder if we use that with virtualbox as well (just for consistency) rather than exec.Run()? What are your thoughts?

**Comment by mattn** [comment]
VirtualBox on windows doesn't modify $PATH. But set $VBOX_MSI_INSTALL_PATH instead.
And vagrant is unix like tool. So it append the path into $PATH.

**Comment by sdomino** [comment]
@mattn great, thanks for clarifying that. I'll go ahead and merge this in

**Pull request merged**
